name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          yarn
          yarn build
      - name: Build and Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SOURCE: "dist/"
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          REMOTE_HOST: caseytimm.com
          REMOTE_USER: github
          TARGET: /srv/web/caseytimm.com
